import bcrypt from 'bcryptjs';
import {
  User,
  Patient,
  Professional,
  BloodPressureRecord,
  GlucoseRecord,
  Medication,
  Appointment,
  ClinicalAlert,
  EducationalContent,
} from '../domain/entities';

// Default hashed passwords
const salt = bcrypt.genSaltSync(10);
const patientPasswordHash = bcrypt.hashSync('paciente123', salt);
const doctorPasswordHash = bcrypt.hashSync('medico123', salt);

export const initialUsers: User[] = [
  {
    id: 'u-patient-maria',
    email: 'maria.silva@email.com',
    passwordHash: patientPasswordHash,
    name: 'Maria Silva',
    role: 'PATIENT',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
  {
    id: 'u-doctor-carlos',
    email: 'carlos.mendes@saude.gov.br',
    passwordHash: doctorPasswordHash,
    name: 'Dr. Carlos Mendes',
    role: 'PROFESSIONAL',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
];

export const initialProfessionals: Professional[] = [
  {
    id: 'prof-carlos',
    userId: 'u-doctor-carlos',
    name: 'Dr. Carlos Mendes',
    email: 'carlos.mendes@saude.gov.br',
    crm: 'CRM 12345',
    specialty: 'Médico de Família e Comunidade',
    healthcareUnit: 'Clínica da Família Santa Marta',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
];

export const initialPatients: Patient[] = [
  {
    id: 'pat-maria',
    userId: 'u-patient-maria',
    name: 'Maria Silva',
    email: 'maria.silva@email.com',
    age: 58,
    gender: 'Feminino',
    conditions: ['HAS', 'DM'],
    riskLevel: 'ALTO',
    healthcareUnit: 'Clínica da Família',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    adherenceRate: 85,
    phone: '(11) 98765-4321',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
  {
    id: 'pat-joao',
    userId: 'u-joao',
    name: 'João da Silva',
    email: 'joao.silva@email.com',
    age: 63,
    gender: 'Masculino',
    conditions: ['HAS'],
    riskLevel: 'ALTO',
    healthcareUnit: 'Clínica da Família',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    adherenceRate: 72,
    phone: '(11) 98111-2233',
    createdAt: '2025-01-10T08:00:00.000Z',
  },
  {
    id: 'pat-anapaula',
    userId: 'u-anapaula',
    name: 'Ana Paula Santos',
    email: 'ana.santos@email.com',
    age: 47,
    gender: 'Feminino',
    conditions: ['DM'],
    riskLevel: 'MODERADO',
    healthcareUnit: 'Clínica da Família',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    adherenceRate: 90,
    phone: '(11) 98222-3344',
    createdAt: '2025-01-15T08:00:00.000Z',
  },
  {
    id: 'pat-carlos-oli',
    userId: 'u-carlos-oli',
    name: 'Carlos Oliveira',
    email: 'carlos.oliveira@email.com',
    age: 60,
    gender: 'Masculino',
    conditions: ['HAS', 'DM'],
    riskLevel: 'MODERADO',
    healthcareUnit: 'Clínica da Família',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    adherenceRate: 80,
    phone: '(11) 98333-4455',
    createdAt: '2025-02-01T08:00:00.000Z',
  },
  {
    id: 'pat-jose',
    userId: 'u-jose',
    name: 'José Pereira',
    email: 'jose.pereira@email.com',
    age: 55,
    gender: 'Masculino',
    conditions: ['HAS'],
    riskLevel: 'BAIXO',
    healthcareUnit: 'Clínica da Família',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    adherenceRate: 95,
    phone: '(11) 98444-5566',
    createdAt: '2025-02-10T08:00:00.000Z',
  },
  {
    id: 'pat-luciana',
    userId: 'u-luciana',
    name: 'Luciana Costa',
    email: 'luciana.costa@email.com',
    age: 49,
    gender: 'Feminino',
    conditions: ['DM'],
    riskLevel: 'BAIXO',
    healthcareUnit: 'Clínica da Família',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    adherenceRate: 92,
    phone: '(11) 98555-6677',
    createdAt: '2025-02-15T08:00:00.000Z',
  },
];

export const initialBloodPressure: BloodPressureRecord[] = [
  {
    id: 'bp-1',
    patientId: 'pat-maria',
    systolic: 120,
    diastolic: 80,
    pulse: 72,
    recordedAt: '2025-05-07T08:30:00.000Z',
    notes: 'Sentindo-se bem após caminhada matinal leve.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-07T08:30:00.000Z',
  },
  {
    id: 'bp-2',
    patientId: 'pat-maria',
    systolic: 118,
    diastolic: 78,
    pulse: 70,
    recordedAt: '2025-05-06T08:15:00.000Z',
    notes: 'Em repouso antes do café.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-06T08:15:00.000Z',
  },
  {
    id: 'bp-3',
    patientId: 'pat-maria',
    systolic: 122,
    diastolic: 82,
    pulse: 74,
    recordedAt: '2025-05-05T08:20:00.000Z',
    notes: 'Rotina normal.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-05T08:20:00.000Z',
  },
  {
    id: 'bp-4',
    patientId: 'pat-maria',
    systolic: 125,
    diastolic: 83,
    pulse: 76,
    recordedAt: '2025-05-04T08:30:00.000Z',
    notes: 'Dia tranquilo.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-04T08:30:00.000Z',
  },
  {
    id: 'bp-5',
    patientId: 'pat-maria',
    systolic: 119,
    diastolic: 79,
    pulse: 71,
    recordedAt: '2025-05-03T08:30:00.000Z',
    notes: 'Aferição regular.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-03T08:30:00.000Z',
  },
  {
    id: 'bp-6',
    patientId: 'pat-maria',
    systolic: 121,
    diastolic: 80,
    pulse: 73,
    recordedAt: '2025-05-02T08:10:00.000Z',
    notes: 'Sem sintomas.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-02T08:10:00.000Z',
  },
  {
    id: 'bp-7',
    patientId: 'pat-maria',
    systolic: 120,
    diastolic: 78,
    pulse: 69,
    recordedAt: '2025-05-01T08:45:00.000Z',
    notes: 'Início do mês.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-01T08:45:00.000Z',
  },
  // Previous spike that generated alert
  {
    id: 'bp-spike',
    patientId: 'pat-maria',
    systolic: 180,
    diastolic: 110,
    pulse: 92,
    recordedAt: '2025-05-07T07:45:00.000Z',
    notes: 'Tontura e dor de cabeça leve ao acordar.',
    isCritical: true,
    statusText: 'Crítica',
    createdAt: '2025-05-07T07:45:00.000Z',
  },
  // João da Silva
  {
    id: 'bp-joao-1',
    patientId: 'pat-joao',
    systolic: 165,
    diastolic: 105,
    pulse: 88,
    recordedAt: '2025-05-06T19:00:00.000Z',
    notes: 'Esqueceu o medicamento.',
    isCritical: true,
    statusText: 'Crítica',
    createdAt: '2025-05-06T19:00:00.000Z',
  },
  // Ana Paula
  {
    id: 'bp-ana-1',
    patientId: 'pat-anapaula',
    systolic: 145,
    diastolic: 95,
    pulse: 78,
    recordedAt: '2025-05-06T14:30:00.000Z',
    notes: 'Pressão um pouco alta no trabalho.',
    isCritical: false,
    statusText: 'Atenção',
    createdAt: '2025-05-06T14:30:00.000Z',
  },
];

export const initialGlucose: GlucoseRecord[] = [
  {
    id: 'glu-1',
    patientId: 'pat-maria',
    glucoseValue: 98,
    moment: 'EM_JEJUM',
    recordedAt: '2025-05-07T07:30:00.000Z',
    notes: 'Glicemia de jejum excelente.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-07T07:30:00.000Z',
  },
  {
    id: 'glu-2',
    patientId: 'pat-maria',
    glucoseValue: 128,
    moment: 'APOS_ALMOCO',
    recordedAt: '2025-05-06T14:00:00.000Z',
    notes: 'Almoço com salada e grelhado.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-06T14:00:00.000Z',
  },
  {
    id: 'glu-3',
    patientId: 'pat-maria',
    glucoseValue: 102,
    moment: 'EM_JEJUM',
    recordedAt: '2025-05-05T07:30:00.000Z',
    notes: 'Controle adequado.',
    isCritical: false,
    statusText: 'Normal',
    createdAt: '2025-05-05T07:30:00.000Z',
  },
  // Previous glucose spike alert
  {
    id: 'glu-spike',
    patientId: 'pat-maria',
    glucoseValue: 215,
    moment: 'APOS_JANTAR',
    recordedAt: '2025-05-06T20:10:00.000Z',
    notes: 'Ingestão de sobremesa com açúcar.',
    isCritical: true,
    statusText: 'Atenção',
    createdAt: '2025-05-06T20:10:00.000Z',
  },
  // João da Silva
  {
    id: 'glu-joao',
    patientId: 'pat-joao',
    glucoseValue: 215,
    moment: 'APOS_JANTAR',
    recordedAt: '2025-05-06T20:10:00.000Z',
    notes: 'Glicemia pós-prandial muito elevada.',
    isCritical: true,
    statusText: 'Crítica',
    createdAt: '2025-05-06T20:10:00.000Z',
  },
  // Carlos Oliveira
  {
    id: 'glu-carlos',
    patientId: 'pat-carlos-oli',
    glucoseValue: 180,
    moment: 'APOS_ALMOCO',
    recordedAt: '2025-05-05T18:20:00.000Z',
    notes: 'Acima do ideal.',
    isCritical: false,
    statusText: 'Atenção',
    createdAt: '2025-05-05T18:20:00.000Z',
  },
];

export const initialMedications: Medication[] = [
  {
    id: 'med-1',
    patientId: 'pat-maria',
    name: 'Losartana Potássica',
    dosage: '50mg',
    frequency: 'Todos os dias',
    reminderTimes: ['08:00'],
    status: 'ATIVO',
    notes: 'Tomar pela manhã com água.',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
  {
    id: 'med-2',
    patientId: 'pat-maria',
    name: 'Hidroclorotiazida',
    dosage: '25mg',
    frequency: 'Todos os dias',
    reminderTimes: ['08:00'],
    status: 'ATIVO',
    notes: 'Diurético matinal.',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
  {
    id: 'med-3',
    patientId: 'pat-maria',
    name: 'Metformina',
    dosage: '850mg',
    frequency: 'Todos os dias',
    reminderTimes: ['08:00', '20:00'],
    status: 'ATIVO',
    notes: 'Tomar junto com as refeições.',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
];

const now = Date.now();
const dayMs = 86400000;

export const initialAppointments: Appointment[] = [
  {
    id: 'app-maria-upcoming',
    patientId: 'pat-maria',
    professionalId: 'prof-carlos',
    patientName: 'Maria Silva',
    patientAge: 58,
    patientConditions: ['HAS', 'DM'],
    appointmentType: 'Retorno Hiperdia',
    scheduledFor: new Date(now + dayMs * 2 + 3600000 * 9).toISOString(),
    clinicName: 'UBS Dr. Manoel de Abreu',
    doctorName: 'Dr. Carlos Mendes',
    status: 'AGENDADA',
    notes: 'Avaliação de controle de pressão arterial e teste de hemoglobina glicada.',
    createdAt: new Date(now - dayMs * 3).toISOString(),
  },
  {
    id: 'app-carlos-today',
    patientId: 'pat-carlos-oli',
    professionalId: 'prof-carlos',
    patientName: 'Carlos Oliveira',
    patientAge: 60,
    patientConditions: ['HAS', 'DM'],
    appointmentType: 'Retorno Clínico',
    scheduledFor: new Date(now + 3600000 * 2).toISOString(),
    clinicName: 'UBS Dr. Manoel de Abreu',
    doctorName: 'Dr. Carlos Mendes',
    status: 'AGENDADA',
    notes: 'Revisão da prescrição de Enalapril e acompanhamento da meta pressórica.',
    createdAt: new Date(now - dayMs * 2).toISOString(),
  },
  {
    id: 'app-joao-upcoming',
    patientId: 'pat-joao',
    professionalId: 'prof-carlos',
    patientName: 'João da Silva',
    patientAge: 63,
    patientConditions: ['HAS'],
    appointmentType: 'Consulta de Rotina',
    scheduledFor: new Date(now + dayMs * 4 + 3600000 * 10).toISOString(),
    clinicName: 'UBS Dr. Manoel de Abreu',
    doctorName: 'Dr. Carlos Mendes',
    status: 'AGENDADA',
    notes: 'Aferição seriada de PA e avaliação renal básica.',
    createdAt: new Date(now - dayMs * 1).toISOString(),
  },
  {
    id: 'app-anapaula-upcoming',
    patientId: 'pat-anapaula',
    professionalId: 'prof-carlos',
    patientName: 'Ana Paula Santos',
    patientAge: 47,
    patientConditions: ['DM'],
    appointmentType: 'Controle Glicêmico',
    scheduledFor: new Date(now + dayMs * 1 + 3600000 * 14).toISOString(),
    clinicName: 'UBS Dr. Manoel de Abreu',
    doctorName: 'Dr. Carlos Mendes',
    status: 'AGENDADA',
    notes: 'Ajuste de dose e acompanhamento de curva glicêmica capilar.',
    createdAt: new Date(now - dayMs * 4).toISOString(),
  },
  {
    id: 'app-luciana-upcoming',
    patientId: 'pat-luciana',
    professionalId: 'prof-carlos',
    patientName: 'Luciana Costa',
    patientAge: 49,
    patientConditions: ['DM'],
    appointmentType: 'Consulta de Rotina',
    scheduledFor: new Date(now + dayMs * 5 + 3600000 * 15).toISOString(),
    clinicName: 'Clínica da Família',
    doctorName: 'Dr. Carlos Mendes',
    status: 'AGENDADA',
    notes: 'Exames laboratoriais de rotina e fundo de olho.',
    createdAt: new Date(now - dayMs * 2).toISOString(),
  },
  {
    id: 'app-maria-past',
    patientId: 'pat-maria',
    professionalId: 'prof-carlos',
    patientName: 'Maria Silva',
    patientAge: 58,
    patientConditions: ['HAS', 'DM'],
    appointmentType: 'Primeira Consulta Hiperdia',
    scheduledFor: new Date(now - dayMs * 25).toISOString(),
    clinicName: 'UBS Dr. Manoel de Abreu',
    doctorName: 'Dr. Carlos Mendes',
    status: 'REALIZADA',
    notes: 'Início do acompanhamento pelo programa Hiperdia municipal. Prescrito Losartana 50mg.',
    createdAt: new Date(now - dayMs * 30).toISOString(),
  },
];

export const initialAlerts: ClinicalAlert[] = [
  {
    id: 'alt-1',
    patientId: 'pat-maria',
    patientName: 'Maria Silva',
    patientAge: 58,
    patientConditions: ['HAS', 'DM'],
    severity: 'CRITICO',
    title: 'Situação crítica: Pressão arterial muito alta',
    message: 'Sua pressão está muito alta. Procure orientação médica ou serviço de pronto atendimento.',
    valueRecorded: '180 / 110 mmHg',
    metricType: 'PRESSURE',
    status: 'PENDENTE',
    triggeredAt: new Date(now - 3600000 * 2).toISOString(),
  },
  {
    id: 'alt-2',
    patientId: 'pat-maria',
    patientName: 'Maria Silva',
    patientAge: 58,
    patientConditions: ['HAS', 'DM'],
    severity: 'ATENCAO',
    title: 'Atenção: Glicemia acima do ideal',
    message: 'Sua glicemia está acima do ideal. Reforce seus cuidados com a alimentação e hidratação.',
    valueRecorded: '215 mg/dL',
    metricType: 'GLUCOSE',
    status: 'PENDENTE',
    triggeredAt: new Date(now - 3600000 * 14).toISOString(),
  },
  {
    id: 'alt-3',
    patientId: 'pat-maria',
    patientName: 'Maria Silva',
    patientAge: 58,
    patientConditions: ['HAS', 'DM'],
    severity: 'INFO',
    title: 'Dica de autocuidado',
    message: 'Reduza o consumo de sal e pratique atividades físicas regularmente conforme orientação médica.',
    valueRecorded: 'Hábito Saudável',
    metricType: 'MEDICATION',
    status: 'PENDENTE',
    triggeredAt: new Date(now - dayMs * 1).toISOString(),
  },
  {
    id: 'alt-4',
    patientId: 'pat-joao',
    patientName: 'João da Silva',
    patientAge: 63,
    patientConditions: ['HAS'],
    severity: 'CRITICO',
    title: 'Glicemia muito alta',
    message: 'Glicemia pós-prandial crítica registrada.',
    valueRecorded: '215 mg/dL',
    metricType: 'GLUCOSE',
    status: 'PENDENTE',
    triggeredAt: new Date(now - 3600000 * 5).toISOString(),
  },
  {
    id: 'alt-5',
    patientId: 'pat-anapaula',
    patientName: 'Ana Paula Santos',
    patientAge: 47,
    patientConditions: ['DM'],
    severity: 'ATENCAO',
    title: 'Pressão acima do ideal',
    message: 'Registro de 145 / 95 mmHg aferido durante a tarde.',
    valueRecorded: '145 / 95 mmHg',
    metricType: 'PRESSURE',
    status: 'PENDENTE',
    triggeredAt: new Date(now - 3600000 * 18).toISOString(),
  },
  {
    id: 'alt-6',
    patientId: 'pat-carlos-oli',
    patientName: 'Carlos Oliveira',
    patientAge: 60,
    patientConditions: ['HAS', 'DM'],
    severity: 'ATENCAO',
    title: 'Glicemia acima do ideal',
    message: 'Registro de 180 mg/dL requer monitoramento.',
    valueRecorded: '180 mg/dL',
    metricType: 'GLUCOSE',
    status: 'PENDENTE',
    triggeredAt: new Date(now - 3600000 * 22).toISOString(),
  },
];

export const initialEducationalContents: EducationalContent[] = [
  {
    id: 'edu-1',
    type: 'MITO',
    category: 'DIABETES',
    title: 'Diabetes tem cura',
    statement: 'O diabetes tipo 2 desaparece completamente com chás e suplementos?',
    explanation: 'FALSO. Diabetes não tem cura definitiva comprovada cientificamente, mas tem tratamento altamente eficaz e pode ser controlado com hábitos saudáveis, medicação adequada e acompanhamento médico.',
    source: 'Sociedade Brasileira de Diabetes (SBD)',
  },
  {
    id: 'edu-2',
    type: 'VERDADE',
    category: 'PRESSAO',
    title: 'Quem tem pressão alta pode fazer exercícios',
    statement: 'A prática regular de exercícios ajuda a baixar a pressão arterial?',
    explanation: 'VERDADE. Atividades físicas aeróbicas moderadas (como caminhadas de 30 minutos) ajudam a dilatar os vasos e controlar a pressão, desde que realizadas com liberação e orientação profissional.',
    source: 'Sociedade Brasileira de Cardiologia (SBC)',
  },
  {
    id: 'edu-3',
    type: 'MITO',
    category: 'PRESSAO',
    title: 'Só sinto quando a pressão está alta',
    statement: 'A pressão alta sempre causa dores de cabeça ou tonturas?',
    explanation: 'FALSO. A hipertensão é chamada de doença silenciosa porque a maioria das pessoas não apresenta sintoma algum até que ocorra uma complicação severa. A única forma de saber é aferir periodicamente.',
    source: 'Ministério da Saúde',
  },
  {
    id: 'edu-4',
    type: 'VERDADE',
    category: 'DIABETES',
    title: 'Comer fibras reduz os picos de glicemia',
    statement: 'Alimentos integrais e vegetais ajudam a controlar a absorção de glicose?',
    explanation: 'VERDADE. As fibras solúveis retardam a digestão dos carboidratos e a absorção de glicose no intestino, evitando picos glicêmicos bruscos após as refeições.',
    source: 'Diretrizes Clínicas de Nutrição',
  },
  {
    id: 'edu-5',
    type: 'MITO',
    category: 'PRESSAO',
    title: 'Posso parar o remédio quando a pressão normalizar',
    statement: 'Se o medidor indicar 120/80 mmHg posso suspender o medicamento?',
    explanation: 'FALSO. A pressão está 120/80 mmHg justamente pelo efeito do medicamento contínuo. Parar sem orientação do médico causa o efeito rebote e elevação perigosa.',
    source: 'Consenso Brasileiro de Hipertensão',
  },
];
